return {
	"dstein64/vim-startuptime",
	"folke/zen-mode.nvim",
	"sbdchd/neoformat",
	"mbbill/undotree",
	"lukas-reineke/indent-blankline.nvim",
	"wakatime/vim-wakatime",
	{ "f-person/git-blame.nvim", enabled = false },
	"luochen1990/rainbow",
	"vimwiki/vimwiki",
	"tpope/vim-repeat",
	"pangloss/vim-javascript",
	"leafgarland/typescript-vim",
	"maxmellon/vim-jsx-pretty",
	"mattn/emmet-vim",
}
